<a href="https://colab.research.google.com/github/ssarinbe24-sys/AI_for_Cybersecurity-/blob/main/Shreya_AI_Cybersecurity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
test=pd.read_csv("/content/sampledata.csv")

In [3]:
test

    url_length  has_https  num_dots  num_special_chars  label
0           15          1         1                  2      0
1           85          0         5                 12      1
2           22          1         2                  1      0
3           95          0         6                 15      1
4           18          1         1                  0      0
5          110          0         7                 18      1
6           30          1         2                  3      0
7           90          0         5                 14      1
8           25          1         2                  2      0
9          100          0         8                 20      1
10          40          1         3                  4      0
11         120          0         9                 22      1
12          28          1         1                  1      0
13          80          0         4                 10      1
14          35          1         2                  2      0
15         105          0         7                 17      1
16          20          1         1                  0      0
17         115          0         8                 19      1
18          45          1         3                  3      0
19          98          0         6                 16      1

In [4]:
test.size

100

In [5]:
test.shape

(20, 5)

In [6]:
test.head(5)

   url_length  has_https  num_dots  num_special_chars  label
0          15          1         1                  2      0
1          85          0         5                 12      1
2          22          1         2                  1      0
3          95          0         6                 15      1
4          18          1         1                  0      0

In [7]:
test.tail(4)

    url_length  has_https  num_dots  num_special_chars  label
16          20          1         1                  0      0
17         115          0         8                 19      1
18          45          1         3                  3      0
19          98          0         6                 16      1

In [8]:
test.sample()

    url_length  has_https  num_dots  num_special_chars  label
17         115          0         8                 19      1

In [9]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   url_length         20 non-null     int64
 1   has_https          20 non-null     int64
 2   num_dots           20 non-null     int64
 3   num_special_chars  20 non-null     int64
 4   label              20 non-null     int64
dtypes: int64(5)
memory usage: 932.0 bytes

In [10]:
test.describe()

       url_length  has_https  num_dots  num_special_chars      label
count   20.000000  20.000000  20.00000          20.000000  20.000000
mean    63.800000   0.500000   4.15000           9.050000   0.500000
std     38.584971   0.512989   2.70039           7.910519   0.512989
min     15.000000   0.000000   1.00000           0.000000   0.000000
25%     27.250000   0.000000   2.00000           2.000000   0.000000
50%     62.500000   0.500000   3.50000           7.000000   0.500000
75%     98.500000   1.000000   6.25000          16.250000   1.000000
max    120.000000   1.000000   9.00000          22.000000   1.000000

In [11]:
test.isnull()

    url_length  has_https  num_dots  num_special_chars  label
0        False      False     False              False  False
1        False      False     False              False  False
2        False      False     False              False  False
3        False      False     False              False  False
4        False      False     False              False  False
5        False      False     False              False  False
6        False      False     False              False  False
7        False      False     False              False  False
8        False      False     False              False  False
9        False      False     False              False  False
10       False      False     False              False  False
11       False      False     False              False  False
12       False      False     False              False  False
13       False      False     False              False  False
14       False      False     False              False  False
15       False      False     False              False  False
16       False      False     False              False  False
17       False      False     False              False  False
18       False      False     False              False  False
19       False      False     False              False  False

In [12]:
test.isnull().sum()

url_length           0
has_https            0
num_dots             0
num_special_chars    0
label                0
dtype: int64

In [13]:
import pandas as pd

In [14]:
school=pd.read_csv("/content/school_data_missing_40_rows.csv")

In [15]:
school.isnull()

    Student_ID   Name  Class  Math_Score  Attendance_%
0        False  False  False       False         False
1        False  False  False       False         False
2        False  False  False       False          True
3        False  False  False       False         False
4        False  False  False        True         False
5        False  False  False       False         False
6        False  False  False       False         False
7        False  False  False       False         False
8        False  False  False       False         False
9        False  False  False       False         False
10       False  False  False       False         False
11       False  False  False       False         False
12       False  False  False       False         False
13       False  False  False       False         False
14       False  False  False        True         False
15       False  False  False       False         False
16       False  False  False       False         False
17       False  False  False       False         False
18       False  False  False       False         False
19       False  False  False       False         False
20       False  False  False       False         False
21       False  False  False       False         False
22       False  False  False       False         False
23       False  False  False       False         False
24       False  False  False       False         False
25       False  False  False       False         False
26       False  False  False       False         False
27       False  False  False       False         False
28       False  False  False       False         False
29       False  False  False       False          True
30       False  False  False       False         False
31       False  False  False       False         False
32       False  False  False       False         False
33       False  False  False        True         False
34       False  False  False       False         False
35       False  False  False       False         False
36       False  False  False        True         False
37       False  False  False       False         False
38       False  False  False       False         False
39       False  False  False        True         False

In [16]:
school.isnull().sum()

Student_ID      0
Name            0
Class           0
Math_Score      5
Attendance_%    2
dtype: int64

In [17]:
school.describe()

           Class  Math_Score  Attendance_%
count  40.000000   35.000000     38.000000
mean    7.950000   74.771429     88.763158
std     1.584379   13.148665      6.918187
min     6.000000   55.000000     78.000000
25%     6.750000   65.000000     82.000000
50%     8.000000   74.000000     90.000000
75%    10.000000   89.000000     95.000000
max    10.000000   93.000000     98.000000

In [18]:
test["label"].value_counts()

label
0    10
1    10
Name: count, dtype: int64

In [19]:
school["Class"].value_counts()

Class
10    11
6     10
7      9
8      5
9      5
Name: count, dtype: int64

In [20]:
X=test.drop("label",axis=1)

In [21]:
X

    url_length  has_https  num_dots  num_special_chars
0           15          1         1                  2
1           85          0         5                 12
2           22          1         2                  1
3           95          0         6                 15
4           18          1         1                  0
5          110          0         7                 18
6           30          1         2                  3
7           90          0         5                 14
8           25          1         2                  2
9          100          0         8                 20
10          40          1         3                  4
11         120          0         9                 22
12          28          1         1                  1
13          80          0         4                 10
14          35          1         2                  2
15         105          0         7                 17
16          20          1         1                  0
17         115          0         8                 19
18          45          1         3                  3
19          98          0         6                 16

In [22]:
y=test["label"]

In [23]:
y

0     0
1     1
2     0
3     1
4     0
5     1
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    1
14    0
15    1
16    0
17    1
18    0
19    1
Name: label, dtype: int64

In [24]:
X=test.drop('label',axis=1)
y=test['label']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [25]:
X_train

    url_length  has_https  num_dots  num_special_chars
5          110          0         7                 18
11         120          0         9                 22
3           95          0         6                 15
18          45          1         3                  3
16          20          1         1                  0
13          80          0         4                 10
2           22          1         2                  1
9          100          0         8                 20
19          98          0         6                 16
4           18          1         1                  0
12          28          1         1                  1
7           90          0         5                 14
10          40          1         3                  4
14          35          1         2                  2
6           30          1         2                  3

In [26]:
y_test

0     0
17    1
15    1
1     1
8     0
Name: label, dtype: int64

In [27]:
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

In [28]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,y_pred)
print(f"accuracy :{accuracy:.2f}")

accuracy :1.00

In [29]:
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.model_selection import train_test_split

Making a ML python format
#####importing library

In [30]:
student=pd.read_csv("/content/student_marks_regression_dataset.csv")

In [31]:
student

   Study_Hours  Marks
0            1     35
1            2     40
2            3     50
3            4     55
4            5     65
5            6     70
6            7     75
7            8     85
8            9     90
9           10     95

In [32]:
student.head(12)

   Study_Hours  Marks
0            1     35
1            2     40
2            3     50
3            4     55
4            5     65
5            6     70
6            7     75
7            8     85
8            9     90
9           10     95

In [33]:
X=student[['Study_Hours']]
y=student['Marks']

In [34]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

lr=LinearRegression()
lr.fit(X_train,y_train)
lr_pred=lr.predict(X_test)
lr_r2=r2_score(y_test,lr_pred)

In [35]:
dt=DecisionTreeRegressor(random_state=42)
dt.fit(X_train,y_train)
dt_pred=dt.predict(X_test)
dt_r2=r2_score(y_test,dt_pred)

In [36]:
rf=RandomForestRegressor()
rf.fit(X_train,y_train)
rf_pred=rf.predict(X_test)
rf_r2=r2_score(y_test,rf_pred)

In [37]:
svm = SVC(random_state=42)
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)
svm_acc = accuracy_score(y_test, svm_pred)

In [38]:
print("Linear Regression R^2 Score:", round(lr_r2,3))
print("Decision Tree Regression R^2 Score:", round(dt_r2,3))
print("Random Forest Regression R^2 Score:", round(rf_r2,3))
print("Support Vector Regression R^2 Score:",round(svm_acc,3))

Linear Regression R^2 Score: 0.994
Decision Tree Regression R^2 Score: 0.96
Random Forest Regression R^2 Score: 0.985
Support Vector Regression R^2 Score: 0.0